SELECT  src.Date,
        src.Ticker,
        src.Open,
        src.Close,
        src.High,
        src.Low,
        src.Volume,
        (src.Open - src.Close) AS retorno,
        (src.Open - src.Close) / src.Open AS retorno_porcentaje,
        ABS(src.High - src.Low) AS amplitud,
        ABS(src.High - src.Low) / src.Open AS amplitud_porcentaje,
        src.CPI,
        src.Unemployment,
        src.Industrial_production,
        src.Fed_funds_rate,
        src.10_year_treasury,
        src.PCE,
        src.DFF,
        src.Target10,
        src.Target5,
        src.Target30
FROM curated as src
WHERE src.Date >= 'date_placeholder'